apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: application
build:
  artifacts:
  - image: simple-app
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - kustomize/base
