apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-pod-scaling-simple-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    #resource:
    #  name: memory
    #  targetAverageValue: 500Mi
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60