apiVersion: v1
kind: Service
metadata:
  name: simple-app
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "app-poc-backend"}'
  labels:
    app: simple-app
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: simple-app