name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    name: Label Issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["coe-review-required"]
            })
