name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
      - labeled
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["coe-review-required"]
            })
            
            
            name: Notify users based on issue labels
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: jenschelkopf/issue-label-notification-action@1.3
          with:
             recipients: |
                  coe-review-required=@capt2101akash
                  help wanted=@capt2101akash
